#!/bin/bash
# MongoDB Setup Helper Script

echo "=========================================="
echo "MongoDB Setup Helper"
echo "=========================================="
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Go to: https://cloud.mongodb.com/"
echo "2. Log in to your account"
echo "3. Check if you have any clusters"
echo ""
echo "If NO clusters exist:"
echo "  - Click 'Build a Database'"
echo "  - Choose 'M0 FREE' tier"
echo "  - Click 'Create Cluster'"
echo "  - Wait 3-5 minutes for provisioning"
echo ""
echo "If cluster EXISTS:"
echo "  - Click 'Connect' on your cluster"
echo "  - Choose 'Connect your application'"
echo "  - Copy the connection string"
echo ""
echo "Then:"
echo "  1. Go to 'Network Access' → Add IP → 'Allow from Anywhere'"
echo "  2. Go to 'Database Access' → Add User:"
echo "     Username: dinusha_nawarathne"
echo "     Password: Dinuser24"
echo ""
echo "Once you have the connection string, update these files:"
echo "  - FC/TourismDigitalFC/.env"
echo "  - sigiriya_tour_guide/.env"
echo ""
echo "Format:"
echo "  MONGODB_URI=mongodb+srv://username:password@cluster0.xxxxx.mongodb.net/?retryWrites=true&w=majority"
echo ""
echo "=========================================="
echo "After updating .env, test with:"
echo "  cd FC/TourismDigitalFC"
echo "  python test_mongodb.py"
echo "=========================================="
